#!/bin/bash -x

# read the docker environment vars
source .env

# update SEAHUBSETTINGS to point to the seahub_settings file
SEAHUBSETTINGS=${SEAFILE_VOLUME}/seafile/conf/seahub_settings.py

# make the path if required
mkdir -p ${SEAFILE_VOLUME}/seafile/conf

# if the settings file does not contain an ENABLE_OAUTH stanza, then pre-seed with OAUTH settings
grep -q "ENABLE_OAUTH = True" ${SEAHUBSETTINGS} 2>/dev/null || cat >> ${SEAHUBSETTINGS} << __EOF
ENABLE_OAUTH = True

# If create new user when he/she logs in Seafile for the first time, defalut `True`.
OAUTH_CREATE_UNKNOWN_USER = True

# If active new user when he/she logs in Seafile for the first time, defalut `True`.
OAUTH_ACTIVATE_USER_AFTER_CREATION = True

# Usually OAuth works through SSL layer. If your server is not parametrized to allow HTTPS, some method will raise an "oauthlib.oauth2.rfc6749.errors.InsecureTransportError". Set this to `True` to avoid this error.
OAUTH_ENABLE_INSECURE_TRANSPORT = False

# Client id/secret generated by authorization server when you register your client application.
OAUTH_CLIENT_ID = "${OAUTH_CLIENT_ID}"
OAUTH_CLIENT_SECRET = "${OAUTH_CLIENT_SECRET}"

# Callback url when user authentication succeeded. Note, the redirect url you input when you register your client application MUST be exactly the same as this value.
OAUTH_REDIRECT_URL = "${SEAFILE_SERVER_PROTOCOL}://${SEAFILE_SERVER_HOSTNAME}/oauth/callback/"

# The following shoud NOT be changed if you are using Google as OAuth provider.
OAUTH_PROVIDER_DOMAIN = "google.com"
OAUTH_AUTHORIZATION_URL = "https://accounts.google.com/o/oauth2/v2/auth"
OAUTH_TOKEN_URL = "https://www.googleapis.com/oauth2/v4/token"
OAUTH_USER_INFO_URL = "https://www.googleapis.com/oauth2/v1/userinfo"
OAUTH_SCOPE = [
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]
OAUTH_ATTRIBUTE_MAP = {
    "id": (True, "uid"),
    "email": (False, "email"),
    "name": (False, "name"),
    "email": (False, "contact_email"),
}
__EOF
