#!/bin/bash

echo $0 running on $(hostname -f)

# read the docker environment vars
echo reading environment from .env, $(cat .env | wc -l) lines
source .env

if test -z "$SEAFILE_VOLUME" ; then
    echo SEAFILE_VOLUME not set
    exit 1
fi


# make the automounter mount the volume (if required)
ls ${SEAFILE_VOLUME} > /dev/null 2> /dev/null

function makedir() {
    if test ! -x "/host/$1" ; then
        echo "creating: $1 on /host"
        mkdir -p "/host/$1"
    else
        echo "exists: $1 on /host"
    fi
}


# make data paths if needed
makedir "${SEAFILE_VOLUME}/seafile/conf"
makedir "${SEAFILE_MYSQL_VOLUME}"
makedir "${SEAFILE_CADDY_VOLUME}" 
makedir "${SEADOC_VOLUME}"

# update SEAHUBSETTINGS to point to the seahub_settings file
SEAHUBSETTINGS=/host/${SEAFILE_VOLUME}/seafile/conf/seahub_settings.py

# if the settings file does not contain an ENABLE_OAUTH stanza, then pre-seed with OAUTH settings
if ! grep -q "ENABLE_OAUTH = True" ${SEAHUBSETTINGS} 2>/dev/null ; then

echo "adding oauth config to ${SEAHUBSETTINGS}"
cat << __EOF >> ${SEAHUBSETTINGS} 
ENABLE_OAUTH = True

# If create new user when he/she logs in Seafile for the first time, default True
OAUTH_CREATE_UNKNOWN_USER = True

# If active new user when he/she logs in Seafile for the first time, default True
OAUTH_ACTIVATE_USER_AFTER_CREATION = True

# Usually OAuth works through SSL layer. If your server is not parametrized to allow HTTPS, some method will raise an "oauthlib.oauth2.rfc6749.errors.InsecureTransportError". Set this to True to avoid this error.
OAUTH_ENABLE_INSECURE_TRANSPORT = False

# Client id/secret generated by authorization server when you register your client application.
OAUTH_CLIENT_ID = "${OAUTH_CLIENT_ID}"
OAUTH_CLIENT_SECRET = "${OAUTH_CLIENT_SECRET}"

# Callback url when user authentication succeeded. Note, the redirect url you input when you register your client application MUST be exactly the same as this value.
OAUTH_REDIRECT_URL = "${SEAFILE_SERVER_PROTOCOL}://${SEAFILE_SERVER_HOSTNAME}/oauth/callback/"

# The following shoud NOT be changed if you are using Google as OAuth provider.
OAUTH_PROVIDER_DOMAIN = "google.com"
OAUTH_AUTHORIZATION_URL = "https://accounts.google.com/o/oauth2/v2/auth"
OAUTH_TOKEN_URL = "https://www.googleapis.com/oauth2/v4/token"
OAUTH_USER_INFO_URL = "https://www.googleapis.com/oauth2/v1/userinfo"
OAUTH_SCOPE = [
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]
OAUTH_ATTRIBUTE_MAP = {
    "id": (True, "uid"),
    "email": (False, "email"),
    "name": (False, "name"),
    "email": (False, "contact_email"),
}
__EOF

else

echo "oauth config found in ${SEAHUBSETTINGS}"

fi

# configure email
if ! grep -q "EMAIL_HOST = " ${SEAHUBSETTINGS} 2>/dev/null ; then

echo "adding email config to ${SEAHUBSETTINGS}"
cat << __EOF_EMAIL >> ${SEAHUBSETTINGS}

# email settings
EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.home.hedgerows.org.uk'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'seafile@hedgerows.org.uk'
SERVER_EMAIL = 'seafile@hedgerows.org.uk'
__EOF_EMAIL

else

echo "email config found in ${SEAHUBSETTINGS}"

fi
